# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cache.fossul.com_fossuls.yaml
- bases/cache.fossul.com_backups.yaml
- bases/cache.fossul.com_restores.yaml
- bases/kubevirt.io.fossul.com_virtualmachines.yaml
#+kubebuilder:scaffold:crdkustomizeresource
