# permissions for end users to edit backupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupschedule-editor-role
rules:
- apiGroups:
  - fossul.io
  resources:
  - backupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fossul.io
  resources:
  - backupschedules/status
  verbs:
  - get
