# permissions for end users to edit fossuls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fossul-editor-role
rules:
- apiGroups:
  - fossul.io
  resources:
  - fossuls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fossul.io
  resources:
  - fossuls/status
  verbs:
  - get
