---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for backup.fossul.io.fossul.io/v1, Kind: Backup
  ##
  - apiGroups:
      - backup.fossul.io.fossul.io
    resources:
      - backups
      - backups/status
      - backups/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for backup.fossul.io.fossul.io/v1, Kind: BackupConfig
  ##
  - apiGroups:
      - backup.fossul.io.fossul.io
    resources:
      - backupconfigs
      - backupconfigs/status
      - backupconfigs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for backup.fossul.io.fossul.io/v1, Kind: BackupSchedule
  ##
  - apiGroups:
      - backup.fossul.io.fossul.io
    resources:
      - backupschedules
      - backupschedules/status
      - backupschedules/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for fossul.io.fossul.io/v1, Kind: Fossul
  ##
  - apiGroups:
      - fossul.io.fossul.io
    resources:
      - fossuls
      - fossuls/status
      - fossuls/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for fossul.io/v1, Kind: Restore
  ##
  - apiGroups:
      - fossul.io
    resources:
      - restores
      - restores/status
      - restores/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules

## Additional rules for fossul
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ""
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
