apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: backup-viewer-role
rules:
- apiGroups:
  - fossul.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fossul.io
  resources:
  - backups/status
  verbs:
  - get
