apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: backupschedule-viewer-role
rules:
- apiGroups:
  - fossul.io
  resources:
  - backupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fossul.io
  resources:
  - backupschedules/status
  verbs:
  - get
