apiVersion: fossul.io/v1
kind: BackupSchedule
metadata:
  name: backupschedule-sample
spec:
  deployment_name: postgresql
  fossul_namespace: fossul
  fossul_server_url: http://fossul-server
  policy: hourly
  cron_schedule: "0/5 * * * *"
  username: admin

