apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: "Create Security Context and add cluster-reader role to Fossul project"
  creationTimestamp: null
  name: fossul-framework-project-permissions
objects:
- apiVersion: v1
  kind: SecurityContextConstraints
  metadata:
    name: ${APPLICATION_NAME}-scc
  allowPrivilegedContainer: false
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  users:
  - system:serviceaccount:${APPLICATION_NAMESPACE}:default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ${APPLICATION_NAME}-${APPLICATION_NAMESPACE}-cluster-reader
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-reader
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: default
    namespace: ${APPLICATION_NAMESPACE}
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: the name and label for all components
    value: fossul
    required: true
  - name: APPLICATION_NAMESPACE
    displayName: Application Namespace or Project
    description: the namespace or project where application will deploy
    value: fossul
    required: true  
